2015-08-29 20:22:22,072 [7] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/8/29 20:22:22
异常发生地址:http://mywww2.wychuan.com/admin/api/account/logon
请求类型:POST
异常:System.OperationCanceledException: 已取消该操作。
   在 System.Threading.CancellationToken.ThrowOperationCanceledException()
   在 System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.OperationCanceledException: 已取消该操作。
   在 System.Threading.CancellationToken.ThrowOperationCanceledException()
   在 System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-08-29 20:22:52,219 [8] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/8/29 20:22:52
异常发生地址:http://mywww2.wychuan.com/admin/api/account/logon
请求类型:POST
异常:System.Threading.Tasks.TaskCanceledException: 已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.Threading.Tasks.TaskCanceledException: 已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-08-29 21:38:20,210 [7] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/8/29 21:38:20
异常发生地址:http://mywww2.wychuan.com/admin/api/account/logon
请求类型:POST
异常:System.OperationCanceledException: 已取消该操作。
   在 System.Threading.CancellationToken.ThrowOperationCanceledException()
   在 System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.OperationCanceledException: 已取消该操作。
   在 System.Threading.CancellationToken.ThrowOperationCanceledException()
   在 System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-08-29 21:39:03,396 [9] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/8/29 21:39:03
异常发生地址:http://mywww2.wychuan.com/admin/api/account/logon
请求类型:POST
异常:System.Threading.Tasks.TaskCanceledException: 已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.Threading.Tasks.TaskCanceledException: 已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-08-29 21:54:36,230 [43] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/8/29 21:54:36
异常发生地址:http://mywww2.wychuan.com/admin/api/account/register
请求类型:POST
异常:System.InvalidOperationException: 在应返回 HttpResponseMessage 实例时返回了 null 值。
   在 System.Web.Http.Controllers.ResponseMessageResultConverter.Convert(HttpControllerContext controllerContext, Object actionResult)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.InvalidOperationException: 在应返回 HttpResponseMessage 实例时返回了 null 值。
   在 System.Web.Http.Controllers.ResponseMessageResultConverter.Convert(HttpControllerContext controllerContext, Object actionResult)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-09-23 15:32:38,545 [25] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/9/23 15:32:38
异常发生地址:http://mywww2.wychuan.com/api/company/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
2015-09-23 15:33:01,457 [19] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/9/23 15:33:01
异常发生地址:http://mywww2.wychuan.com/api/company/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
2015-09-23 15:34:15,134 [15] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/9/23 15:34:15
异常发生地址:http://mywww2.wychuan.com/api/company/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
2015-09-23 15:35:29,862 [23] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/9/23 15:35:29
异常发生地址:http://mywww2.wychuan.com/api/company/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
2015-09-23 15:35:33,612 [18] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/9/23 15:35:33
异常发生地址:http://mywww2.wychuan.com/api/company/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
2015-09-23 15:35:37,932 [17] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/9/23 15:35:37
异常发生地址:http://mywww2.wychuan.com/api/company/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'Creator' 无效。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.Tools.CompanyDao.Insert(CompanyDTO companyDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\Tools\CompanyDao.cs:行号 35
   在 AC.Service.Impl.Tools.CompanyService.Create(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\Tools\CompanyService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.CompanyController.Save(CompanyDTO company) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\CompanyController.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:3f4cc8b2-a581-46b0-a4f2-452c4eee646d
2015-10-13 20:29:38,757 [76] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/10/13 20:29:38
异常发生地址:http://mywww2.wychuan.com/api/items/saveitems
请求类型:POST
异常:System.IO.InvalidDataException: [AsserUtils-Greater] failed with arg1:-1 arg2:0, -1<=0
   在 AC.Util.AssertUtils.Greater(Int64 arg1, Int64 arg2, String message) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Core\Util\AssertUtils.cs:行号 165
   在 AC.Util.AssertUtils.Greater(Int32 arg1, Int32 arg2) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Core\Util\AssertUtils.cs:行号 140
   在 AC.Service.Impl.LiCai.ItemsService.Rename(Int32 id, String name) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\ItemsService.cs:行号 34
   在 wychuan2.com.Areas.admin.Controllers.api.ItemsController.SaveItems(ItemDTO item) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\ItemsController.cs:行号 77
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.IO.InvalidDataException: [AsserUtils-Greater] failed with arg1:-1 arg2:0, -1<=0
   在 AC.Util.AssertUtils.Greater(Int64 arg1, Int64 arg2, String message) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Core\Util\AssertUtils.cs:行号 165
   在 AC.Util.AssertUtils.Greater(Int32 arg1, Int32 arg2) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Core\Util\AssertUtils.cs:行号 140
   在 AC.Service.Impl.LiCai.ItemsService.Rename(Int32 id, String name) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\ItemsService.cs:行号 34
   在 wychuan2.com.Areas.admin.Controllers.api.ItemsController.SaveItems(ItemDTO item) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\ItemsController.cs:行号 77
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-10-22 19:54:10,959 [11] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/10/22 19:54:10
异常发生地址:http://mywww2.wychuan.com/api/bill/fastsave
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 必须声明标量变量 "@Category"。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.Insert(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 50
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 18
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.FastSave(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 46
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:54e95d7d-1fd0-47d5-9402-06b3a125c9b7
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 必须声明标量变量 "@Category"。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.Insert(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 50
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 18
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.FastSave(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 46
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:54e95d7d-1fd0-47d5-9402-06b3a125c9b7
2015-10-22 20:33:50,048 [29] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/10/22 20:33:50
异常发生地址:http://mywww2.wychuan.com/api/bill/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 不能将值 NULL 插入列 'SecondCategory'，表 'WYC.dbo.LC_BillDetails'；列不允许有 Null 值。INSERT 失败。
语句已终止。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.Insert(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 48
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 18
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 30
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:fde3f072-e371-4af4-95b1-97a056b62b60
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 不能将值 NULL 插入列 'SecondCategory'，表 'WYC.dbo.LC_BillDetails'；列不允许有 Null 值。INSERT 失败。
语句已终止。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.Insert(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 48
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 18
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 30
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:fde3f072-e371-4af4-95b1-97a056b62b60
2015-10-29 15:52:59,446 [42] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/10/29 15:52:59
异常发生地址:http://mywww2.wychuan.com/api/bill/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 不能将值 NULL 插入列 'SecondCategory'，表 'WYC.dbo.LC_BillDetails'；列不允许有 Null 值。INSERT 失败。
语句已终止。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.Insert(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 55
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 27
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 31
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:7bbad3ea-fc5f-417c-a1e0-aec0a2384c1f
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 不能将值 NULL 插入列 'SecondCategory'，表 'WYC.dbo.LC_BillDetails'；列不允许有 Null 值。INSERT 失败。
语句已终止。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.Insert(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 55
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 27
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 31
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:7bbad3ea-fc5f-417c-a1e0-aec0a2384c1f
2015-10-29 17:06:29,157 [32] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/10/29 17:06:29
异常发生地址:http://mywww2.wychuan.com/api/bill/save
请求类型:POST
异常:System.Data.SqlTypes.SqlTypeException: SqlDateTime 溢出。必须介于 1/1/1753 12:00:00 AM 和 12/31/9999 11:59:59 PM 之间。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.HasBalanceAdjust(Int32 userId, DateTime startTime) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 125
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 31
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.Data.SqlTypes.SqlTypeException: SqlDateTime 溢出。必须介于 1/1/1753 12:00:00 AM 和 12/31/9999 11:59:59 PM 之间。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.HasBalanceAdjust(Int32 userId, DateTime startTime) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 125
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 31
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-10-29 17:07:31,788 [46] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/10/29 17:07:31
异常发生地址:http://mywww2.wychuan.com/api/bill/save
请求类型:POST
异常:System.Data.SqlTypes.SqlTypeException: SqlDateTime 溢出。必须介于 1/1/1753 12:00:00 AM 和 12/31/9999 11:59:59 PM 之间。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.HasBalanceAdjust(Int32 userId, DateTime startTime) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 125
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 31
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.Data.SqlTypes.SqlTypeException: SqlDateTime 溢出。必须介于 1/1/1753 12:00:00 AM 和 12/31/9999 11:59:59 PM 之间。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.LiCai.BillDao.HasBalanceAdjust(Int32 userId, DateTime startTime) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\BillDao.cs:行号 125
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.Save(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 31
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-11-12 20:14:33,205 [23] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/11/12 20:14:33
异常发生地址:http://mywww2.wychuan.com/api/bill/adjustbalance
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'IsBalanceAdjust' 无效。
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, CommandType commandType, String commandText, Int32 timeOutInSeconds, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 391
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, String commandText, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 321
   在 AC.Dao.LiCai.AccountDao.ChangeBalance(Int32 id, Decimal balance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\AccountDao.cs:行号 118
   在 AC.Service.Impl.LiCai.AccountService.ChangeBalance(Int32 accountId, Decimal balance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\AccountService.cs:行号 116
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.AdjustBalance(AccountBalanceAdjustModel adjustParam) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 101
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:e0a09389-6874-4e5d-9baf-c4f0d6adc0f9
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'IsBalanceAdjust' 无效。
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, CommandType commandType, String commandText, Int32 timeOutInSeconds, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 391
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, String commandText, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 321
   在 AC.Dao.LiCai.AccountDao.ChangeBalance(Int32 id, Decimal balance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\AccountDao.cs:行号 118
   在 AC.Service.Impl.LiCai.AccountService.ChangeBalance(Int32 accountId, Decimal balance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\AccountService.cs:行号 116
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.AdjustBalance(AccountBalanceAdjustModel adjustParam) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 101
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:e0a09389-6874-4e5d-9baf-c4f0d6adc0f9
2015-11-12 20:38:38,222 [8] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/11/12 20:38:38
异常发生地址:http://mywww2.wychuan.com/api/bill/adjustbalance
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 列名 'IsBalanceAdjust' 无效。
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, CommandType commandType, String commandText, Int32 timeOutInSeconds, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 391
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, String commandText, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 321
   在 AC.Dao.LiCai.AccountDao.AdjustBalance(Int32 id, Decimal adjustPrice, Boolean isAdjustBalance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\AccountDao.cs:行号 108
   在 AC.Service.Impl.LiCai.AccountService.AdjustBalance(Int32 accountId, Decimal price, Boolean isAdjustBalance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\AccountService.cs:行号 111
   在 AC.Service.Impl.LiCai.AdjustBalanceProvider.Adjust() 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\AdjustBalanceProvider.cs:行号 74
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 32
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.AdjustBalance(AccountBalanceAdjustModel adjustParam) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 114
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:5040551f-5aed-413e-bbdb-971fcacc2a69
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 列名 'IsBalanceAdjust' 无效。
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, CommandType commandType, String commandText, Int32 timeOutInSeconds, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 391
   在 AC.Data.DbHelper.ExecuteNonQuery(String connString, String commandText, IDbParameters parameters) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 321
   在 AC.Dao.LiCai.AccountDao.AdjustBalance(Int32 id, Decimal adjustPrice, Boolean isAdjustBalance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\LiCai\AccountDao.cs:行号 108
   在 AC.Service.Impl.LiCai.AccountService.AdjustBalance(Int32 accountId, Decimal price, Boolean isAdjustBalance) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\AccountService.cs:行号 111
   在 AC.Service.Impl.LiCai.AdjustBalanceProvider.Adjust() 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\AdjustBalanceProvider.cs:行号 74
   在 AC.Service.Impl.LiCai.BillService.Create(BillDTO bill) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\LiCai\BillService.cs:行号 32
   在 wychuan2.com.Areas.admin.Controllers.api.BillController.AdjustBalance(AccountBalanceAdjustModel adjustParam) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\BillController.cs:行号 114
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:5040551f-5aed-413e-bbdb-971fcacc2a69
2015-11-17 11:45:15,862 [6] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/11/17 11:45:15
异常发生地址:http://mywww2.wychuan.com/api/account/disable
请求类型:POST
异常:System.InvalidOperationException: 无法将多个参数(“userId”和“disable”)绑定到请求的内容。
   在 System.Web.Http.Controllers.HttpActionBinding.ExecuteBindingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--------------------end---------------------

System.InvalidOperationException: 无法将多个参数(“userId”和“disable”)绑定到请求的内容。
   在 System.Web.Http.Controllers.HttpActionBinding.ExecuteBindingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-11-17 13:51:38,271 [27] ERROR ErrorLog [(null)] - 
-----------------start----------------------
2015/11/17 13:51:38
异常发生地址:http://mywww2.wychuan.com/api/menu/save
请求类型:POST
异常:System.Data.SqlClient.SqlException (0x80131904): 不能将值 NULL 插入列 'Url'，表 'WYC.dbo.Menu'；列不允许有 Null 值。INSERT 失败。
语句已终止。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.User.MenuDao.Insert(MenuDTO menuDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\User\MenuDao.cs:行号 30
   在 AC.Service.Impl.User.MenuService.Create(MenuDTO menuDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\User\MenuService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.MenuController.Save(MenuDTO menu) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\MenuController.cs:行号 23
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:92bff7b0-389b-4fbe-9455-2d626f809b07
--------------------end---------------------

System.Data.SqlClient.SqlException (0x80131904): 不能将值 NULL 插入列 'Url'，表 'WYC.dbo.Menu'；列不允许有 Null 值。INSERT 失败。
语句已终止。
   在 AC.Data.DbHelper.ExecuteScalar(String connString, CommandType commandType, String commandText, Int32 timeoutInSeconds, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 485
   在 AC.Data.DbHelper.ExecuteScalar(String connString, String commandText, IDbParameters parameterValues) 位置 e:\wyc\github\achuan.lib\net\net.libs\AC.Data\Data\DblHelper.cs:行号 417
   在 AC.Dao.User.MenuDao.Insert(MenuDTO menuDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Dao\User\MenuDao.cs:行号 30
   在 AC.Service.Impl.User.MenuService.Create(MenuDTO menuDTO) 位置 e:\wyc\github\wychuan.com\src\wychuan\AC.Service.Impl\User\MenuService.cs:行号 22
   在 wychuan2.com.Areas.admin.Controllers.api.MenuController.Save(MenuDTO menu) 位置 e:\wyc\github\wychuan.com\src\wychuan\wychuan2.com\Areas\admin\Controllers\api\MenuController.cs:行号 23
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
ClientConnectionId:92bff7b0-389b-4fbe-9455-2d626f809b07
